<a href="https://colab.research.google.com/github/sahanal2603/TensorflowPractice/blob/main/TensorflowIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install tensorflow

In [3]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [10]:
string = tf.Variable("HElllo", tf.string)
rank0 = tf.Variable(345,tf.int32)

In [30]:
rank1 = tf.Variable(["Ram", "Raj"], tf.string)
rank2 = tf.Variable([[10,20,30], [40,50,60]],tf.int32)
rank3 = tf.Variable([[[11, 22, 33], [44, 55, 66]], [[45, 56, 23], [56, 78, 66]]],tf.int32)
rank4 = tf.Variable([[[[1,2,3,4,5],[0,9,8,7,6]],[[11,22,33,44,55],[00,88,66,99,77]]],
                     [[[1,2,3,5,6],[11,22,33,44,55]],[[12,34,56,78,90],[23,56,78,12,9]]],[[[1,2,3,4,5],[1,2,3,4,5]],[[34,56,78,90,12],[90,45,67,12,34]]]],tf.int32)

In [31]:
tf.rank(rank4)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [32]:
rank4.shape

TensorShape([3, 2, 2, 5])

In [55]:
tensor1 = tf.zeros([1,2,3])
tensor2 = tf.reshape(tensor1,([1,2,1,1,-1]))
tensor3 = tf.reshape(tensor1,([3,-1]))

In [56]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[[[0. 0. 0.]]]


  [[[0. 0. 0.]]]]], shape=(1, 2, 1, 1, 3), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [68]:
#Evaluating Tensors
with tf.compat.v1.Session() as sess:
  tensor1 = tf.zeros([1,2,3])
  print(tensor1)
  print(tensor1.eval())

Tensor("zeros_3:0", shape=(1, 2, 3), dtype=float32)
[[[0. 0. 0.]
  [0. 0. 0.]]]


In [76]:
t = tf.ones([3,3,3,3])
print(t)
t = tf.reshape(t,[27,-1])
print(t)

tf.Tensor(
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]], shape=(3, 3, 3, 3), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(27, 3), dtype=float32)
